version: '3.8'
services:
  api:
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  bo:
    build: ./admin
    ports:
      - "3001:3000"
    volumes:
      - ./admin:/app
      - /app/node_modules
    command: npm run dev

  public:
    build: ./public-app
    ports:
      - "3002:3000"
    volumes:
      - ./public-app:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=verbose

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - bo
      - public